/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppInvitatieRouteImport } from './routes/_app/invitatie'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppSemneazaTokenRouteImport } from './routes/_app/semneaza.$token'
import { Route as AppAutentificareLayoutRouteImport } from './routes/_app/autentificare/_layout'
import { Route as AppAutentificareLayoutIndexRouteImport } from './routes/_app/autentificare/_layout.index'
import { Route as AppContractCompleteazaTokenRouteImport } from './routes/_app/contract.completeaza.$token'
import { Route as AppAuthPanouLayoutRouteImport } from './routes/_app/_auth/panou/_layout'
import { Route as AppAuthBunVenitLayoutRouteImport } from './routes/_app/_auth/bun-venit/_layout'
import { Route as AppAuthPanouLayoutIndexRouteImport } from './routes/_app/_auth/panou/_layout.index'
import { Route as AppAuthBunVenitLayoutIndexRouteImport } from './routes/_app/_auth/bun-venit/_layout.index'
import { Route as AppAuthPanouLayoutSetariRouteImport } from './routes/_app/_auth/panou/_layout.setari'
import { Route as AppAuthPanouLayoutSabloaneRouteImport } from './routes/_app/_auth/panou/_layout.sabloane'
import { Route as AppAuthPanouLayoutAuditRouteImport } from './routes/_app/_auth/panou/_layout.audit'
import { Route as AppAuthPanouLayoutSetariIndexRouteImport } from './routes/_app/_auth/panou/_layout.setari.index'
import { Route as AppAuthPanouLayoutSabloaneIndexRouteImport } from './routes/_app/_auth/panou/_layout.sabloane.index'
import { Route as AppAuthPanouLayoutSetariProfilRouteImport } from './routes/_app/_auth/panou/_layout.setari.profil'
import { Route as AppAuthPanouLayoutSetariOrganizatieRouteImport } from './routes/_app/_auth/panou/_layout.setari.organizatie'
import { Route as AppAuthPanouLayoutSetariAbonamentRouteImport } from './routes/_app/_auth/panou/_layout.setari.abonament'
import { Route as AppAuthPanouLayoutSabloaneNouRouteImport } from './routes/_app/_auth/panou/_layout.sabloane.nou'
import { Route as AppAuthPanouLayoutContracteNouRouteImport } from './routes/_app/_auth/panou/_layout.contracte.nou'
import { Route as AppAuthPanouLayoutContracteContractIdRouteImport } from './routes/_app/_auth/panou/_layout.contracte.$contractId'
import { Route as AppAuthPanouLayoutSabloaneTemplateIdEditeazaRouteImport } from './routes/_app/_auth/panou/_layout.sabloane.$templateId.editeaza'
import { Route as AppAuthPanouLayoutSabloaneTemplateIdContracteRouteImport } from './routes/_app/_auth/panou/_layout.sabloane.$templateId.contracte'
import { Route as AppAuthPanouLayoutContracteActAditionalNouRouteImport } from './routes/_app/_auth/panou/_layout.contracte.act-aditional.nou'
import { Route as AppAuthPanouLayoutContracteContractIdEditeazaRouteImport } from './routes/_app/_auth/panou/_layout.contracte.$contractId.editeaza'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvitatieRoute = AppInvitatieRouteImport.update({
  id: '/invitatie',
  path: '/invitatie',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppSemneazaTokenRoute = AppSemneazaTokenRouteImport.update({
  id: '/semneaza/$token',
  path: '/semneaza/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppAutentificareLayoutRoute = AppAutentificareLayoutRouteImport.update({
  id: '/autentificare/_layout',
  path: '/autentificare',
  getParentRoute: () => AppRoute,
} as any)
const AppAutentificareLayoutIndexRoute =
  AppAutentificareLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAutentificareLayoutRoute,
  } as any)
const AppContractCompleteazaTokenRoute =
  AppContractCompleteazaTokenRouteImport.update({
    id: '/contract/completeaza/$token',
    path: '/contract/completeaza/$token',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthPanouLayoutRoute = AppAuthPanouLayoutRouteImport.update({
  id: '/panou/_layout',
  path: '/panou',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthBunVenitLayoutRoute = AppAuthBunVenitLayoutRouteImport.update({
  id: '/bun-venit/_layout',
  path: '/bun-venit',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthPanouLayoutIndexRoute = AppAuthPanouLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthPanouLayoutRoute,
} as any)
const AppAuthBunVenitLayoutIndexRoute =
  AppAuthBunVenitLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthBunVenitLayoutRoute,
  } as any)
const AppAuthPanouLayoutSetariRoute =
  AppAuthPanouLayoutSetariRouteImport.update({
    id: '/setari',
    path: '/setari',
    getParentRoute: () => AppAuthPanouLayoutRoute,
  } as any)
const AppAuthPanouLayoutSabloaneRoute =
  AppAuthPanouLayoutSabloaneRouteImport.update({
    id: '/sabloane',
    path: '/sabloane',
    getParentRoute: () => AppAuthPanouLayoutRoute,
  } as any)
const AppAuthPanouLayoutAuditRoute = AppAuthPanouLayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAuthPanouLayoutRoute,
} as any)
const AppAuthPanouLayoutSetariIndexRoute =
  AppAuthPanouLayoutSetariIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthPanouLayoutSetariRoute,
  } as any)
const AppAuthPanouLayoutSabloaneIndexRoute =
  AppAuthPanouLayoutSabloaneIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthPanouLayoutSabloaneRoute,
  } as any)
const AppAuthPanouLayoutSetariProfilRoute =
  AppAuthPanouLayoutSetariProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AppAuthPanouLayoutSetariRoute,
  } as any)
const AppAuthPanouLayoutSetariOrganizatieRoute =
  AppAuthPanouLayoutSetariOrganizatieRouteImport.update({
    id: '/organizatie',
    path: '/organizatie',
    getParentRoute: () => AppAuthPanouLayoutSetariRoute,
  } as any)
const AppAuthPanouLayoutSetariAbonamentRoute =
  AppAuthPanouLayoutSetariAbonamentRouteImport.update({
    id: '/abonament',
    path: '/abonament',
    getParentRoute: () => AppAuthPanouLayoutSetariRoute,
  } as any)
const AppAuthPanouLayoutSabloaneNouRoute =
  AppAuthPanouLayoutSabloaneNouRouteImport.update({
    id: '/nou',
    path: '/nou',
    getParentRoute: () => AppAuthPanouLayoutSabloaneRoute,
  } as any)
const AppAuthPanouLayoutContracteNouRoute =
  AppAuthPanouLayoutContracteNouRouteImport.update({
    id: '/contracte/nou',
    path: '/contracte/nou',
    getParentRoute: () => AppAuthPanouLayoutRoute,
  } as any)
const AppAuthPanouLayoutContracteContractIdRoute =
  AppAuthPanouLayoutContracteContractIdRouteImport.update({
    id: '/contracte/$contractId',
    path: '/contracte/$contractId',
    getParentRoute: () => AppAuthPanouLayoutRoute,
  } as any)
const AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute =
  AppAuthPanouLayoutSabloaneTemplateIdEditeazaRouteImport.update({
    id: '/$templateId/editeaza',
    path: '/$templateId/editeaza',
    getParentRoute: () => AppAuthPanouLayoutSabloaneRoute,
  } as any)
const AppAuthPanouLayoutSabloaneTemplateIdContracteRoute =
  AppAuthPanouLayoutSabloaneTemplateIdContracteRouteImport.update({
    id: '/$templateId/contracte',
    path: '/$templateId/contracte',
    getParentRoute: () => AppAuthPanouLayoutSabloaneRoute,
  } as any)
const AppAuthPanouLayoutContracteActAditionalNouRoute =
  AppAuthPanouLayoutContracteActAditionalNouRouteImport.update({
    id: '/contracte/act-aditional/nou',
    path: '/contracte/act-aditional/nou',
    getParentRoute: () => AppAuthPanouLayoutRoute,
  } as any)
const AppAuthPanouLayoutContracteContractIdEditeazaRoute =
  AppAuthPanouLayoutContracteContractIdEditeazaRouteImport.update({
    id: '/editeaza',
    path: '/editeaza',
    getParentRoute: () => AppAuthPanouLayoutContracteContractIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitatie': typeof AppInvitatieRoute
  '/autentificare': typeof AppAutentificareLayoutRouteWithChildren
  '/semneaza/$token': typeof AppSemneazaTokenRoute
  '/bun-venit': typeof AppAuthBunVenitLayoutRouteWithChildren
  '/panou': typeof AppAuthPanouLayoutRouteWithChildren
  '/contract/completeaza/$token': typeof AppContractCompleteazaTokenRoute
  '/autentificare/': typeof AppAutentificareLayoutIndexRoute
  '/panou/audit': typeof AppAuthPanouLayoutAuditRoute
  '/panou/sabloane': typeof AppAuthPanouLayoutSabloaneRouteWithChildren
  '/panou/setari': typeof AppAuthPanouLayoutSetariRouteWithChildren
  '/bun-venit/': typeof AppAuthBunVenitLayoutIndexRoute
  '/panou/': typeof AppAuthPanouLayoutIndexRoute
  '/panou/contracte/$contractId': typeof AppAuthPanouLayoutContracteContractIdRouteWithChildren
  '/panou/contracte/nou': typeof AppAuthPanouLayoutContracteNouRoute
  '/panou/sabloane/nou': typeof AppAuthPanouLayoutSabloaneNouRoute
  '/panou/setari/abonament': typeof AppAuthPanouLayoutSetariAbonamentRoute
  '/panou/setari/organizatie': typeof AppAuthPanouLayoutSetariOrganizatieRoute
  '/panou/setari/profil': typeof AppAuthPanouLayoutSetariProfilRoute
  '/panou/sabloane/': typeof AppAuthPanouLayoutSabloaneIndexRoute
  '/panou/setari/': typeof AppAuthPanouLayoutSetariIndexRoute
  '/panou/contracte/$contractId/editeaza': typeof AppAuthPanouLayoutContracteContractIdEditeazaRoute
  '/panou/contracte/act-aditional/nou': typeof AppAuthPanouLayoutContracteActAditionalNouRoute
  '/panou/sabloane/$templateId/contracte': typeof AppAuthPanouLayoutSabloaneTemplateIdContracteRoute
  '/panou/sabloane/$templateId/editeaza': typeof AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitatie': typeof AppInvitatieRoute
  '/semneaza/$token': typeof AppSemneazaTokenRoute
  '/contract/completeaza/$token': typeof AppContractCompleteazaTokenRoute
  '/autentificare': typeof AppAutentificareLayoutIndexRoute
  '/panou/audit': typeof AppAuthPanouLayoutAuditRoute
  '/bun-venit': typeof AppAuthBunVenitLayoutIndexRoute
  '/panou': typeof AppAuthPanouLayoutIndexRoute
  '/panou/contracte/$contractId': typeof AppAuthPanouLayoutContracteContractIdRouteWithChildren
  '/panou/contracte/nou': typeof AppAuthPanouLayoutContracteNouRoute
  '/panou/sabloane/nou': typeof AppAuthPanouLayoutSabloaneNouRoute
  '/panou/setari/abonament': typeof AppAuthPanouLayoutSetariAbonamentRoute
  '/panou/setari/organizatie': typeof AppAuthPanouLayoutSetariOrganizatieRoute
  '/panou/setari/profil': typeof AppAuthPanouLayoutSetariProfilRoute
  '/panou/sabloane': typeof AppAuthPanouLayoutSabloaneIndexRoute
  '/panou/setari': typeof AppAuthPanouLayoutSetariIndexRoute
  '/panou/contracte/$contractId/editeaza': typeof AppAuthPanouLayoutContracteContractIdEditeazaRoute
  '/panou/contracte/act-aditional/nou': typeof AppAuthPanouLayoutContracteActAditionalNouRoute
  '/panou/sabloane/$templateId/contracte': typeof AppAuthPanouLayoutSabloaneTemplateIdContracteRoute
  '/panou/sabloane/$templateId/editeaza': typeof AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/invitatie': typeof AppInvitatieRoute
  '/_app/autentificare/_layout': typeof AppAutentificareLayoutRouteWithChildren
  '/_app/semneaza/$token': typeof AppSemneazaTokenRoute
  '/_app/_auth/bun-venit/_layout': typeof AppAuthBunVenitLayoutRouteWithChildren
  '/_app/_auth/panou/_layout': typeof AppAuthPanouLayoutRouteWithChildren
  '/_app/contract/completeaza/$token': typeof AppContractCompleteazaTokenRoute
  '/_app/autentificare/_layout/': typeof AppAutentificareLayoutIndexRoute
  '/_app/_auth/panou/_layout/audit': typeof AppAuthPanouLayoutAuditRoute
  '/_app/_auth/panou/_layout/sabloane': typeof AppAuthPanouLayoutSabloaneRouteWithChildren
  '/_app/_auth/panou/_layout/setari': typeof AppAuthPanouLayoutSetariRouteWithChildren
  '/_app/_auth/bun-venit/_layout/': typeof AppAuthBunVenitLayoutIndexRoute
  '/_app/_auth/panou/_layout/': typeof AppAuthPanouLayoutIndexRoute
  '/_app/_auth/panou/_layout/contracte/$contractId': typeof AppAuthPanouLayoutContracteContractIdRouteWithChildren
  '/_app/_auth/panou/_layout/contracte/nou': typeof AppAuthPanouLayoutContracteNouRoute
  '/_app/_auth/panou/_layout/sabloane/nou': typeof AppAuthPanouLayoutSabloaneNouRoute
  '/_app/_auth/panou/_layout/setari/abonament': typeof AppAuthPanouLayoutSetariAbonamentRoute
  '/_app/_auth/panou/_layout/setari/organizatie': typeof AppAuthPanouLayoutSetariOrganizatieRoute
  '/_app/_auth/panou/_layout/setari/profil': typeof AppAuthPanouLayoutSetariProfilRoute
  '/_app/_auth/panou/_layout/sabloane/': typeof AppAuthPanouLayoutSabloaneIndexRoute
  '/_app/_auth/panou/_layout/setari/': typeof AppAuthPanouLayoutSetariIndexRoute
  '/_app/_auth/panou/_layout/contracte/$contractId/editeaza': typeof AppAuthPanouLayoutContracteContractIdEditeazaRoute
  '/_app/_auth/panou/_layout/contracte/act-aditional/nou': typeof AppAuthPanouLayoutContracteActAditionalNouRoute
  '/_app/_auth/panou/_layout/sabloane/$templateId/contracte': typeof AppAuthPanouLayoutSabloaneTemplateIdContracteRoute
  '/_app/_auth/panou/_layout/sabloane/$templateId/editeaza': typeof AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitatie'
    | '/autentificare'
    | '/semneaza/$token'
    | '/bun-venit'
    | '/panou'
    | '/contract/completeaza/$token'
    | '/autentificare/'
    | '/panou/audit'
    | '/panou/sabloane'
    | '/panou/setari'
    | '/bun-venit/'
    | '/panou/'
    | '/panou/contracte/$contractId'
    | '/panou/contracte/nou'
    | '/panou/sabloane/nou'
    | '/panou/setari/abonament'
    | '/panou/setari/organizatie'
    | '/panou/setari/profil'
    | '/panou/sabloane/'
    | '/panou/setari/'
    | '/panou/contracte/$contractId/editeaza'
    | '/panou/contracte/act-aditional/nou'
    | '/panou/sabloane/$templateId/contracte'
    | '/panou/sabloane/$templateId/editeaza'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitatie'
    | '/semneaza/$token'
    | '/contract/completeaza/$token'
    | '/autentificare'
    | '/panou/audit'
    | '/bun-venit'
    | '/panou'
    | '/panou/contracte/$contractId'
    | '/panou/contracte/nou'
    | '/panou/sabloane/nou'
    | '/panou/setari/abonament'
    | '/panou/setari/organizatie'
    | '/panou/setari/profil'
    | '/panou/sabloane'
    | '/panou/setari'
    | '/panou/contracte/$contractId/editeaza'
    | '/panou/contracte/act-aditional/nou'
    | '/panou/sabloane/$templateId/contracte'
    | '/panou/sabloane/$templateId/editeaza'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/invitatie'
    | '/_app/autentificare/_layout'
    | '/_app/semneaza/$token'
    | '/_app/_auth/bun-venit/_layout'
    | '/_app/_auth/panou/_layout'
    | '/_app/contract/completeaza/$token'
    | '/_app/autentificare/_layout/'
    | '/_app/_auth/panou/_layout/audit'
    | '/_app/_auth/panou/_layout/sabloane'
    | '/_app/_auth/panou/_layout/setari'
    | '/_app/_auth/bun-venit/_layout/'
    | '/_app/_auth/panou/_layout/'
    | '/_app/_auth/panou/_layout/contracte/$contractId'
    | '/_app/_auth/panou/_layout/contracte/nou'
    | '/_app/_auth/panou/_layout/sabloane/nou'
    | '/_app/_auth/panou/_layout/setari/abonament'
    | '/_app/_auth/panou/_layout/setari/organizatie'
    | '/_app/_auth/panou/_layout/setari/profil'
    | '/_app/_auth/panou/_layout/sabloane/'
    | '/_app/_auth/panou/_layout/setari/'
    | '/_app/_auth/panou/_layout/contracte/$contractId/editeaza'
    | '/_app/_auth/panou/_layout/contracte/act-aditional/nou'
    | '/_app/_auth/panou/_layout/sabloane/$templateId/contracte'
    | '/_app/_auth/panou/_layout/sabloane/$templateId/editeaza'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/invitatie': {
      id: '/_app/invitatie'
      path: '/invitatie'
      fullPath: '/invitatie'
      preLoaderRoute: typeof AppInvitatieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/semneaza/$token': {
      id: '/_app/semneaza/$token'
      path: '/semneaza/$token'
      fullPath: '/semneaza/$token'
      preLoaderRoute: typeof AppSemneazaTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/autentificare/_layout': {
      id: '/_app/autentificare/_layout'
      path: '/autentificare'
      fullPath: '/autentificare'
      preLoaderRoute: typeof AppAutentificareLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/autentificare/_layout/': {
      id: '/_app/autentificare/_layout/'
      path: '/'
      fullPath: '/autentificare/'
      preLoaderRoute: typeof AppAutentificareLayoutIndexRouteImport
      parentRoute: typeof AppAutentificareLayoutRoute
    }
    '/_app/contract/completeaza/$token': {
      id: '/_app/contract/completeaza/$token'
      path: '/contract/completeaza/$token'
      fullPath: '/contract/completeaza/$token'
      preLoaderRoute: typeof AppContractCompleteazaTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/panou/_layout': {
      id: '/_app/_auth/panou/_layout'
      path: '/panou'
      fullPath: '/panou'
      preLoaderRoute: typeof AppAuthPanouLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/bun-venit/_layout': {
      id: '/_app/_auth/bun-venit/_layout'
      path: '/bun-venit'
      fullPath: '/bun-venit'
      preLoaderRoute: typeof AppAuthBunVenitLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/panou/_layout/': {
      id: '/_app/_auth/panou/_layout/'
      path: '/'
      fullPath: '/panou/'
      preLoaderRoute: typeof AppAuthPanouLayoutIndexRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/bun-venit/_layout/': {
      id: '/_app/_auth/bun-venit/_layout/'
      path: '/'
      fullPath: '/bun-venit/'
      preLoaderRoute: typeof AppAuthBunVenitLayoutIndexRouteImport
      parentRoute: typeof AppAuthBunVenitLayoutRoute
    }
    '/_app/_auth/panou/_layout/setari': {
      id: '/_app/_auth/panou/_layout/setari'
      path: '/setari'
      fullPath: '/panou/setari'
      preLoaderRoute: typeof AppAuthPanouLayoutSetariRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/panou/_layout/sabloane': {
      id: '/_app/_auth/panou/_layout/sabloane'
      path: '/sabloane'
      fullPath: '/panou/sabloane'
      preLoaderRoute: typeof AppAuthPanouLayoutSabloaneRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/panou/_layout/audit': {
      id: '/_app/_auth/panou/_layout/audit'
      path: '/audit'
      fullPath: '/panou/audit'
      preLoaderRoute: typeof AppAuthPanouLayoutAuditRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/panou/_layout/setari/': {
      id: '/_app/_auth/panou/_layout/setari/'
      path: '/'
      fullPath: '/panou/setari/'
      preLoaderRoute: typeof AppAuthPanouLayoutSetariIndexRouteImport
      parentRoute: typeof AppAuthPanouLayoutSetariRoute
    }
    '/_app/_auth/panou/_layout/sabloane/': {
      id: '/_app/_auth/panou/_layout/sabloane/'
      path: '/'
      fullPath: '/panou/sabloane/'
      preLoaderRoute: typeof AppAuthPanouLayoutSabloaneIndexRouteImport
      parentRoute: typeof AppAuthPanouLayoutSabloaneRoute
    }
    '/_app/_auth/panou/_layout/setari/profil': {
      id: '/_app/_auth/panou/_layout/setari/profil'
      path: '/profil'
      fullPath: '/panou/setari/profil'
      preLoaderRoute: typeof AppAuthPanouLayoutSetariProfilRouteImport
      parentRoute: typeof AppAuthPanouLayoutSetariRoute
    }
    '/_app/_auth/panou/_layout/setari/organizatie': {
      id: '/_app/_auth/panou/_layout/setari/organizatie'
      path: '/organizatie'
      fullPath: '/panou/setari/organizatie'
      preLoaderRoute: typeof AppAuthPanouLayoutSetariOrganizatieRouteImport
      parentRoute: typeof AppAuthPanouLayoutSetariRoute
    }
    '/_app/_auth/panou/_layout/setari/abonament': {
      id: '/_app/_auth/panou/_layout/setari/abonament'
      path: '/abonament'
      fullPath: '/panou/setari/abonament'
      preLoaderRoute: typeof AppAuthPanouLayoutSetariAbonamentRouteImport
      parentRoute: typeof AppAuthPanouLayoutSetariRoute
    }
    '/_app/_auth/panou/_layout/sabloane/nou': {
      id: '/_app/_auth/panou/_layout/sabloane/nou'
      path: '/nou'
      fullPath: '/panou/sabloane/nou'
      preLoaderRoute: typeof AppAuthPanouLayoutSabloaneNouRouteImport
      parentRoute: typeof AppAuthPanouLayoutSabloaneRoute
    }
    '/_app/_auth/panou/_layout/contracte/nou': {
      id: '/_app/_auth/panou/_layout/contracte/nou'
      path: '/contracte/nou'
      fullPath: '/panou/contracte/nou'
      preLoaderRoute: typeof AppAuthPanouLayoutContracteNouRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/panou/_layout/contracte/$contractId': {
      id: '/_app/_auth/panou/_layout/contracte/$contractId'
      path: '/contracte/$contractId'
      fullPath: '/panou/contracte/$contractId'
      preLoaderRoute: typeof AppAuthPanouLayoutContracteContractIdRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/panou/_layout/sabloane/$templateId/editeaza': {
      id: '/_app/_auth/panou/_layout/sabloane/$templateId/editeaza'
      path: '/$templateId/editeaza'
      fullPath: '/panou/sabloane/$templateId/editeaza'
      preLoaderRoute: typeof AppAuthPanouLayoutSabloaneTemplateIdEditeazaRouteImport
      parentRoute: typeof AppAuthPanouLayoutSabloaneRoute
    }
    '/_app/_auth/panou/_layout/sabloane/$templateId/contracte': {
      id: '/_app/_auth/panou/_layout/sabloane/$templateId/contracte'
      path: '/$templateId/contracte'
      fullPath: '/panou/sabloane/$templateId/contracte'
      preLoaderRoute: typeof AppAuthPanouLayoutSabloaneTemplateIdContracteRouteImport
      parentRoute: typeof AppAuthPanouLayoutSabloaneRoute
    }
    '/_app/_auth/panou/_layout/contracte/act-aditional/nou': {
      id: '/_app/_auth/panou/_layout/contracte/act-aditional/nou'
      path: '/contracte/act-aditional/nou'
      fullPath: '/panou/contracte/act-aditional/nou'
      preLoaderRoute: typeof AppAuthPanouLayoutContracteActAditionalNouRouteImport
      parentRoute: typeof AppAuthPanouLayoutRoute
    }
    '/_app/_auth/panou/_layout/contracte/$contractId/editeaza': {
      id: '/_app/_auth/panou/_layout/contracte/$contractId/editeaza'
      path: '/editeaza'
      fullPath: '/panou/contracte/$contractId/editeaza'
      preLoaderRoute: typeof AppAuthPanouLayoutContracteContractIdEditeazaRouteImport
      parentRoute: typeof AppAuthPanouLayoutContracteContractIdRoute
    }
  }
}

interface AppAuthBunVenitLayoutRouteChildren {
  AppAuthBunVenitLayoutIndexRoute: typeof AppAuthBunVenitLayoutIndexRoute
}

const AppAuthBunVenitLayoutRouteChildren: AppAuthBunVenitLayoutRouteChildren = {
  AppAuthBunVenitLayoutIndexRoute: AppAuthBunVenitLayoutIndexRoute,
}

const AppAuthBunVenitLayoutRouteWithChildren =
  AppAuthBunVenitLayoutRoute._addFileChildren(
    AppAuthBunVenitLayoutRouteChildren,
  )

interface AppAuthPanouLayoutSabloaneRouteChildren {
  AppAuthPanouLayoutSabloaneNouRoute: typeof AppAuthPanouLayoutSabloaneNouRoute
  AppAuthPanouLayoutSabloaneIndexRoute: typeof AppAuthPanouLayoutSabloaneIndexRoute
  AppAuthPanouLayoutSabloaneTemplateIdContracteRoute: typeof AppAuthPanouLayoutSabloaneTemplateIdContracteRoute
  AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute: typeof AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute
}

const AppAuthPanouLayoutSabloaneRouteChildren: AppAuthPanouLayoutSabloaneRouteChildren =
  {
    AppAuthPanouLayoutSabloaneNouRoute: AppAuthPanouLayoutSabloaneNouRoute,
    AppAuthPanouLayoutSabloaneIndexRoute: AppAuthPanouLayoutSabloaneIndexRoute,
    AppAuthPanouLayoutSabloaneTemplateIdContracteRoute:
      AppAuthPanouLayoutSabloaneTemplateIdContracteRoute,
    AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute:
      AppAuthPanouLayoutSabloaneTemplateIdEditeazaRoute,
  }

const AppAuthPanouLayoutSabloaneRouteWithChildren =
  AppAuthPanouLayoutSabloaneRoute._addFileChildren(
    AppAuthPanouLayoutSabloaneRouteChildren,
  )

interface AppAuthPanouLayoutSetariRouteChildren {
  AppAuthPanouLayoutSetariAbonamentRoute: typeof AppAuthPanouLayoutSetariAbonamentRoute
  AppAuthPanouLayoutSetariOrganizatieRoute: typeof AppAuthPanouLayoutSetariOrganizatieRoute
  AppAuthPanouLayoutSetariProfilRoute: typeof AppAuthPanouLayoutSetariProfilRoute
  AppAuthPanouLayoutSetariIndexRoute: typeof AppAuthPanouLayoutSetariIndexRoute
}

const AppAuthPanouLayoutSetariRouteChildren: AppAuthPanouLayoutSetariRouteChildren =
  {
    AppAuthPanouLayoutSetariAbonamentRoute:
      AppAuthPanouLayoutSetariAbonamentRoute,
    AppAuthPanouLayoutSetariOrganizatieRoute:
      AppAuthPanouLayoutSetariOrganizatieRoute,
    AppAuthPanouLayoutSetariProfilRoute: AppAuthPanouLayoutSetariProfilRoute,
    AppAuthPanouLayoutSetariIndexRoute: AppAuthPanouLayoutSetariIndexRoute,
  }

const AppAuthPanouLayoutSetariRouteWithChildren =
  AppAuthPanouLayoutSetariRoute._addFileChildren(
    AppAuthPanouLayoutSetariRouteChildren,
  )

interface AppAuthPanouLayoutContracteContractIdRouteChildren {
  AppAuthPanouLayoutContracteContractIdEditeazaRoute: typeof AppAuthPanouLayoutContracteContractIdEditeazaRoute
}

const AppAuthPanouLayoutContracteContractIdRouteChildren: AppAuthPanouLayoutContracteContractIdRouteChildren =
  {
    AppAuthPanouLayoutContracteContractIdEditeazaRoute:
      AppAuthPanouLayoutContracteContractIdEditeazaRoute,
  }

const AppAuthPanouLayoutContracteContractIdRouteWithChildren =
  AppAuthPanouLayoutContracteContractIdRoute._addFileChildren(
    AppAuthPanouLayoutContracteContractIdRouteChildren,
  )

interface AppAuthPanouLayoutRouteChildren {
  AppAuthPanouLayoutAuditRoute: typeof AppAuthPanouLayoutAuditRoute
  AppAuthPanouLayoutSabloaneRoute: typeof AppAuthPanouLayoutSabloaneRouteWithChildren
  AppAuthPanouLayoutSetariRoute: typeof AppAuthPanouLayoutSetariRouteWithChildren
  AppAuthPanouLayoutIndexRoute: typeof AppAuthPanouLayoutIndexRoute
  AppAuthPanouLayoutContracteContractIdRoute: typeof AppAuthPanouLayoutContracteContractIdRouteWithChildren
  AppAuthPanouLayoutContracteNouRoute: typeof AppAuthPanouLayoutContracteNouRoute
  AppAuthPanouLayoutContracteActAditionalNouRoute: typeof AppAuthPanouLayoutContracteActAditionalNouRoute
}

const AppAuthPanouLayoutRouteChildren: AppAuthPanouLayoutRouteChildren = {
  AppAuthPanouLayoutAuditRoute: AppAuthPanouLayoutAuditRoute,
  AppAuthPanouLayoutSabloaneRoute: AppAuthPanouLayoutSabloaneRouteWithChildren,
  AppAuthPanouLayoutSetariRoute: AppAuthPanouLayoutSetariRouteWithChildren,
  AppAuthPanouLayoutIndexRoute: AppAuthPanouLayoutIndexRoute,
  AppAuthPanouLayoutContracteContractIdRoute:
    AppAuthPanouLayoutContracteContractIdRouteWithChildren,
  AppAuthPanouLayoutContracteNouRoute: AppAuthPanouLayoutContracteNouRoute,
  AppAuthPanouLayoutContracteActAditionalNouRoute:
    AppAuthPanouLayoutContracteActAditionalNouRoute,
}

const AppAuthPanouLayoutRouteWithChildren =
  AppAuthPanouLayoutRoute._addFileChildren(AppAuthPanouLayoutRouteChildren)

interface AppAuthRouteChildren {
  AppAuthBunVenitLayoutRoute: typeof AppAuthBunVenitLayoutRouteWithChildren
  AppAuthPanouLayoutRoute: typeof AppAuthPanouLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthBunVenitLayoutRoute: AppAuthBunVenitLayoutRouteWithChildren,
  AppAuthPanouLayoutRoute: AppAuthPanouLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppAutentificareLayoutRouteChildren {
  AppAutentificareLayoutIndexRoute: typeof AppAutentificareLayoutIndexRoute
}

const AppAutentificareLayoutRouteChildren: AppAutentificareLayoutRouteChildren =
  {
    AppAutentificareLayoutIndexRoute: AppAutentificareLayoutIndexRoute,
  }

const AppAutentificareLayoutRouteWithChildren =
  AppAutentificareLayoutRoute._addFileChildren(
    AppAutentificareLayoutRouteChildren,
  )

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppInvitatieRoute: typeof AppInvitatieRoute
  AppAutentificareLayoutRoute: typeof AppAutentificareLayoutRouteWithChildren
  AppSemneazaTokenRoute: typeof AppSemneazaTokenRoute
  AppContractCompleteazaTokenRoute: typeof AppContractCompleteazaTokenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppInvitatieRoute: AppInvitatieRoute,
  AppAutentificareLayoutRoute: AppAutentificareLayoutRouteWithChildren,
  AppSemneazaTokenRoute: AppSemneazaTokenRoute,
  AppContractCompleteazaTokenRoute: AppContractCompleteazaTokenRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
